package com.watabelabs.gepg.mappers.bill;

import java.time.LocalDateTime;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.watabelabs.gepg.utils.LocalDateTimeAdapter;

/**
 * The GepgBillTrxInfoCtrlNoReuseMapper class is used for mapping the XML
 * response
 * to the corresponding Java object. This class represents the bill transaction
 * information.
 *
 *
 *
 * <p>
 * It contains four fields: billId, payCntrNum, trxSts, and trxSts
 * ode. These fields
 * store the bill ID, payment
 * control number, transaction status, and transaction
 * status code, respectively.
 * </p>
 *
 *
 * <p>
 * The class is annotated with JAXB annotations to specify how the XML elemen
 * s
 * should be mapped to the Java fields. It uses {@link XmlRootElement} to defin
 * root elemen
 * t name and {@link XmlAccessorType} to specify the access type for
 * the fields.
 * </p>
 */

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class GepgBillTrxInfoCtrlNoReuse {

    @XmlElement(name = "BillId", required = true)
    private String billId;

    @XmlElement(name = "SubSpCode", required = true)
    private String subSpCode;

    @XmlElement(name = "SpSysId", required = true)
    private String spSysId;

    @XmlElement(name = "BillAmt", required = true)
    private double billAmt;

    @XmlElement(name = "MiscAmt", required = true)
    private double miscAmt;

    @XmlElement(name = "BillExprDt", required = true)
    @XmlJavaTypeAdapter(LocalDateTimeAdapter.class)
    private LocalDateTime billExprDt;

    @XmlElement(name = "PyrId", required = true)
    private String pyrId;

    @XmlElement(name = "PyrName", required = true)
    private String pyrName;

    @XmlElement(name = "BillDesc", required = true)
    private String billDesc;

    @XmlElement(name = "BillGenDt", required = true)
    @XmlJavaTypeAdapter(LocalDateTimeAdapter.class)
    private LocalDateTime billGenDt;

    @XmlElement(name = "BillGenBy", required = true)
    private String billGenBy;

    @XmlElement(name = "BillApprBy", required = true)
    private String billApprBy;

    @XmlElement(name = "PyrCellNum", required = true)
    private String pyrCellNum;

    @XmlElement(name = "PyrEmail", required = true)
    private String pyrEmail;

    @XmlElement(name = "Ccy", required = true)
    private String ccy;

    @XmlElement(name = "BillEqvAmt", required = true)
    private double billEqvAmt;

    @XmlElement(name = "RemFlag", required = true)
    private boolean remFlag;

    @XmlElement(name = "BillPayOpt", required = true)
    private int billPayOpt;

    @XmlElement(name = "PayCntrNum", required = true)
    private int payCntrNum;

    @XmlElementWrapper(name = "BillItems")
    @XmlElement(name = "BillItem", required = true)
    private List<GepgBillItem> billItems;

    /**
     * Default no-args constructor.
     */
    public GepgBillTrxInfoCtrlNoReuse() {
    }

    /**
     * All-args constructor.
     *
     * @param billId          the bill ID
     * @param subSpCode       the sub service provider code
     * @param spSysId         the service provider system ID
     * @param billAmt         the bill amount
     * @param miscAmt         the miscellaneous amount
     * @param billExprDt      the bill expiration date
     * @param pyrId           the payer ID
     * @param pyrName         the payer name
     * @param billDesc        the bill description
     * @param billGenDt       the bill generation date
     * @param billGenBy       the bill generated by
     * @param billApprBy      the bill approved by
     * @param pyrCellNum      the payer cell number
     * @param pyrEmail        the payer email
     * @param ccy             the currency
     * @param billEqvAmt      the bill equivalent amount
     * @param remFlag         the reminder flag
     * @param billPayOpt      the bill payment option
     * @param billPayCntrNumb the bill payment control number
     * @param billItems       the list of bill items
     */
    public GepgBillTrxInfoCtrlNoReuse(String billId, String subSpCode, String spSysId, double billAmt,
            double miscAmt,
            LocalDateTime billExprDt,
            String pyrId, String pyrName, String billDesc, LocalDateTime billGenDt, String billGenBy, String billApprBy,
            String pyrCellNum, String pyrEmail, String ccy, double billEqvAmt, boolean remFlag, int billPayOpt,
            int payCntrNum, List<GepgBillItem> billItems) {
        this.billId = billId;
        this.subSpCode = subSpCode;
        this.spSysId = spSysId;
        this.billAmt = billAmt;
        this.miscAmt = miscAmt;
        this.billExprDt = billExprDt;
        this.pyrId = pyrId;
        this.pyrName = pyrName;
        this.billDesc = billDesc;
        this.billGenDt = billGenDt;
        this.billGenBy = billGenBy;
        this.billApprBy = billApprBy;
        this.pyrCellNum = pyrCellNum;
        this.pyrEmail = pyrEmail;
        this.ccy = ccy;
        this.billEqvAmt = billEqvAmt;
        this.remFlag = remFlag;
        this.billPayOpt = billPayOpt;
        this.payCntrNum = payCntrNum;
        this.billItems = billItems;
    }

    // Getters and Setters

    // (Include getters and setters for all fields)

    /**
     * Generates a string representation of the object.
     *
     * @return a string representation of the object
     */
    @Override
    public String toString() {
        return "BillTrxInf{" +
                "billId='" + billId + '\'' +
                ", subSpCode='" + subSpCode + '\'' +
                ", spSysId='" + spSysId + '\'' +
                ", billAmt=" + billAmt +
                ", miscAmt=" + miscAmt +
                ", billExprDt=" + billExprDt +
                ", pyrId='" + pyrId + '\'' +
                ", pyrName='" + pyrName + '\'' +
                ", billDesc='" + billDesc + '\'' +
                ", billGenDt=" + billGenDt +
                ", billGenBy='" + billGenBy + '\'' +
                ", billApprBy='" + billApprBy + '\'' +
                ", pyrCellNum='" + pyrCellNum + '\'' +
                ", pyrEmail='" + pyrEmail + '\'' +
                ", ccy='" + ccy + '\'' +
                ", billEqvAmt=" + billEqvAmt +
                ", remFlag=" + remFlag +
                ", billPayOpt=" + billPayOpt +
                ", billItems=" + billItems +
                '}';
    }

    /**
     * Checks if this object is equal to another object.
     *
     * @param o the other object
     * @return true if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;

        GepgBillTrxInfoCtrlNoReuse that = (GepgBillTrxInfoCtrlNoReuse) o;

        if (Double.compare(that.billAmt, billAmt) != 0)
            return false;
        if (Double.compare(that.miscAmt, miscAmt) != 0)
            return false;
        if (remFlag != that.remFlag)
            return false;
        if (billPayOpt != that.billPayOpt)
            return false;
        if (billId != null ? !billId.equals(that.billId) : that.billId != null)
            return false;
        if (subSpCode != null ? !subSpCode.equals(that.subSpCode) : that.subSpCode != null)
            return false;
        if (spSysId != null ? !spSysId.equals(that.spSysId) : that.spSysId != null)
            return false;
        if (billExprDt != null ? !billExprDt.equals(that.billExprDt) : that.billExprDt != null)
            return false;
        if (pyrId != null ? !pyrId.equals(that.pyrId) : that.pyrId != null)
            return false;
        if (pyrName != null ? !pyrName.equals(that.pyrName) : that.pyrName != null)
            return false;
        if (billDesc != null ? !billDesc.equals(that.billDesc) : that.billDesc != null)
            return false;
        if (billGenDt != null ? !billGenDt.equals(that.billGenDt) : that.billGenDt != null)
            return false;
        if (billGenBy != null ? !billGenBy.equals(that.billGenBy) : that.billGenBy != null)
            return false;
        if (billApprBy != null ? !billApprBy.equals(that.billApprBy) : that.billApprBy != null)
            return false;
        if (pyrCellNum != null ? !pyrCellNum.equals(that.pyrCellNum) : that.pyrCellNum != null)
            return false;
        if (pyrEmail != null ? !pyrEmail.equals(that.pyrEmail) : that.pyrEmail != null)
            return false;
        if (ccy != null ? !ccy.equals(that.ccy) : that.ccy != null)
            return false;
        if (Double.compare(that.billEqvAmt, billEqvAmt) != 0)
            return false;
        return billItems != null ? billItems.equals(that.billItems) : that.billItems == null;
    }

    /**
     * Generates a hash code for this object.
     *
     * @return a hash code for this object
     */
    @Override
    public int hashCode() {
        int result;
        long temp;
        result = billId != null ? billId.hashCode() : 0;
        result = 31 * result + (subSpCode != null ? subSpCode.hashCode() : 0);
        result = 31 * result + (spSysId != null ? spSysId.hashCode() : 0);
        temp = Double.doubleToLongBits(billAmt);
        result = 31 * result + (int) (temp ^ (temp >>> 32));
        temp = Double.doubleToLongBits(miscAmt);
        result = 31 * result + (int) (temp ^ (temp >>> 32));
        result = 31 * result + (billExprDt != null ? billExprDt.hashCode() : 0);
        result = 31 * result + (pyrId != null ? pyrId.hashCode() : 0);
        result = 31 * result + (pyrName != null ? pyrName.hashCode() : 0);
        result = 31 * result + (billDesc != null ? billDesc.hashCode() : 0);
        result = 31 * result + (billGenDt != null ? billGenDt.hashCode() : 0);
        result = 31 * result + (billGenBy != null ? billGenBy.hashCode() : 0);
        result = 31 * result + (billApprBy != null ? billApprBy.hashCode() : 0);
        result = 31 * result + (pyrCellNum != null ? pyrCellNum.hashCode() : 0);
        result = 31 * result + (pyrEmail != null ? pyrEmail.hashCode() : 0);
        result = 31 * result + (ccy != null ? ccy.hashCode() : 0);
        temp = Double.doubleToLongBits(billEqvAmt);
        result = 31 * result + (int) (temp ^ (temp >>> 32));
        result = 31 * result + (remFlag ? 1 : 0);
        result = 31 * result + billPayOpt;
        result = 31 * result + (billItems != null ? billItems.hashCode() : 0);
        return result;
    }

    public String getBillId() {
        return billId;
    }

    public void setBillId(String billId) {
        this.billId = billId;
    }

    public String getSubSpCode() {
        return subSpCode;
    }

    public void setSubSpCode(String subSpCode) {
        this.subSpCode = subSpCode;
    }

    public String getSpSysId() {
        return spSysId;
    }

    public void setSpSysId(String spSysId) {
        this.spSysId = spSysId;
    }

    public double getBillAmt() {
        return billAmt;
    }

    public void setBillAmt(double billAmt) {
        this.billAmt = billAmt;
    }

    public double getMiscAmt() {
        return miscAmt;
    }

    public void setMiscAmt(double miscAmt) {
        this.miscAmt = miscAmt;
    }

    public LocalDateTime getBillExprDt() {
        return billExprDt;
    }

    public void setBillExprDt(LocalDateTime billExprDt) {
        this.billExprDt = billExprDt;
    }

    public String getPyrId() {
        return pyrId;
    }

    public void setPyrId(String pyrId) {
        this.pyrId = pyrId;
    }

    public String getPyrName() {
        return pyrName;
    }

    public void setPyrName(String pyrName) {
        this.pyrName = pyrName;
    }

    public String getBillDesc() {
        return billDesc;
    }

    public void setBillDesc(String billDesc) {
        this.billDesc = billDesc;
    }

    public LocalDateTime getBillGenDt() {
        return billGenDt;
    }

    public void setBillGenDt(LocalDateTime billGenDt) {
        this.billGenDt = billGenDt;
    }

    public String getBillGenBy() {
        return billGenBy;
    }

    public void setBillGenBy(String billGenBy) {
        this.billGenBy = billGenBy;
    }

    public String getBillApprBy() {
        return billApprBy;
    }

    public void setBillApprBy(String billApprBy) {
        this.billApprBy = billApprBy;
    }

    public String getPyrCellNum() {
        return pyrCellNum;
    }

    public void setPyrCellNum(String pyrCellNum) {
        this.pyrCellNum = pyrCellNum;
    }

    public String getPyrEmail() {
        return pyrEmail;
    }

    public void setPyrEmail(String pyrEmail) {
        this.pyrEmail = pyrEmail;
    }

    public String getCcy() {
        return ccy;
    }

    public void setCcy(String ccy) {
        this.ccy = ccy;
    }

    public double getBillEqvAmt() {
        return billEqvAmt;
    }

    public void setBillEqvAmt(double billEqvAmt) {
        this.billEqvAmt = billEqvAmt;
    }

    public boolean isRemFlag() {
        return remFlag;
    }

    public void setRemFlag(boolean remFlag) {
        this.remFlag = remFlag;
    }

    public int getBillPayOpt() {
        return billPayOpt;
    }

    public void setBillPayOpt(int billPayOpt) {
        this.billPayOpt = billPayOpt;
    }

    public int getPayCntrNum() {
        return payCntrNum;
    }

    public void setPayCntrNum(int payCntrNum) {
        this.payCntrNum = payCntrNum;
    }

    public List<GepgBillItem> getBillItems() {
        return billItems;
    }

    public void setBillItems(List<GepgBillItem> billItems) {
        this.billItems = billItems;
    }
}
