package com.watabelabs.gepg.mappers.bill.requests;

import java.util.List;
import java.util.UUID;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * The GepgBillTrxInf class is used for mapping the XML response
 * to the corresponding Java object. This class represents the bill transaction
 * information.
 *
 * <p>
 * It contains fields to store the bill ID, payment control number, transaction
 * status, and transaction status code, among others.
 * </p>
 *
 * <p>
 * The class is annotated with JAXB annotations to specify how the XML elements
 * should be mapped to the Java fields. It uses {@link XmlRootElement} to define
 * the root element name and {@link XmlAccessorType} to specify the access type
 * for the fields.
 * </p>
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class GepgBillTrxInf {

    @XmlElement(name = "BillId", required = true)
    private UUID billId;

    @XmlElement(name = "SubSpCode", required = true)
    private String subSpCode;

    @XmlElement(name = "SpSysId", required = true)
    private String spSysId;

    @XmlElement(name = "BillAmt", required = true)
    private Double billAmt;

    @XmlElement(name = "MiscAmt", required = true)
    private Double miscAmt;

    @XmlElement(name = "BillExprDt", required = true)
    private String billExprDt;

    @XmlElement(name = "PyrId", required = true)
    private String pyrId;

    @XmlElement(name = "PyrName", required = true)
    private String pyrName;

    @XmlElement(name = "BillDesc", required = true)
    private String billDesc;

    @XmlElement(name = "BillGenDt", required = true)
    private String billGenDt;

    @XmlElement(name = "BillGenBy", required = true)
    private String billGenBy;

    @XmlElement(name = "BillApprBy", required = true)
    private String billApprBy;

    @XmlElement(name = "PyrCellNum", required = true)
    private String pyrCellNum;

    @XmlElement(name = "PyrEmail", required = true)
    private String pyrEmail;

    @XmlElement(name = "Ccy", required = true)
    private String ccy;

    @XmlElement(name = "BillEqvAmt", required = true)
    private Double billEqvAmt;

    @XmlElement(name = "RemFlag", required = true)
    private boolean remFlag;

    @XmlElement(name = "BillPayOpt", required = true)
    private int billPayOpt;

    @XmlElement(name = "PayCntrNum", required = false)
    private String payCntrNum;

    @XmlElementWrapper(name = "BillItems")
    @XmlElement(name = "BillItem", required = true)
    private List<GepgBillItem> billItems;

    /**
     * Default no-args constructor.
     */
    public GepgBillTrxInf() {
    }

    /**
     * All-args constructor except payCntrNum.
     * use this when doing a Bill submition, as the control number is not needed
     *
     * @param billId     the bill ID
     * @param subSpCode  the sub service provider code
     * @param spSysId    the service provider system ID
     * @param billAmt    the bill amount
     * @param miscAmt    the miscellaneous amount
     * @param billExprDt the bill expiration date
     * @param pyrId      the payer ID
     * @param pyrName    the payer name
     * @param billDesc   the bill description
     * @param billGenDt  the bill generation date
     * @param billGenBy  the bill generated by
     * @param billApprBy the bill approved by
     * @param pyrCellNum the payer cell number
     * @param pyrEmail   the payer email
     * @param ccy        the currency
     * @param billEqvAmt the bill equivalent amount
     * @param remFlag    the reminder flag
     * @param billPayOpt the bill payment option
     * @param billItems  the list of bill items
     */
    public GepgBillTrxInf(UUID billId, String subSpCode, String spSysId, Double billAmt, Double miscAmt,
            String billExprDt, String pyrId, String pyrName, String billDesc, String billGenDt,
            String billGenBy, String billApprBy, String pyrCellNum, String pyrEmail, String ccy,
            Double billEqvAmt, boolean remFlag, int billPayOpt, List<GepgBillItem> billItems) {
        this.billId = billId;
        this.subSpCode = subSpCode;
        this.spSysId = spSysId;
        this.billAmt = billAmt;
        this.miscAmt = miscAmt;
        this.billExprDt = billExprDt;
        this.pyrId = pyrId;
        this.pyrName = pyrName;
        this.billDesc = billDesc;
        this.billGenDt = billGenDt;
        this.billGenBy = billGenBy;
        this.billApprBy = billApprBy;
        this.pyrCellNum = pyrCellNum;
        this.pyrEmail = pyrEmail;
        this.ccy = ccy;
        this.billEqvAmt = billEqvAmt;
        this.remFlag = remFlag;
        this.billPayOpt = billPayOpt;
        this.billItems = billItems;
    }

    /**
     * All-args constructor including payCntrNum.
     * use this when doing a control number reuse submition, as the control number
     * is needed
     *
     * @param billId     the bill ID
     * @param subSpCode  the sub service provider code
     * @param spSysId    the service provider system ID
     * @param billAmt    the bill amount
     * @param miscAmt    the miscellaneous amount
     * @param billExprDt the bill expiration date
     * @param pyrId      the payer ID
     * @param pyrName    the payer name
     * @param billDesc   the bill description
     * @param billGenDt  the bill generation date
     * @param billGenBy  the bill generated by
     * @param billApprBy the bill approved by
     * @param pyrCellNum the payer cell number
     * @param pyrEmail   the payer email
     * @param ccy        the currency
     * @param billEqvAmt the bill equivalent amount
     * @param remFlag    the reminder flag
     * @param billPayOpt the bill payment option
     * @param payCntrNum the payment control number
     * @param billItems  the list of bill items
     */
    public GepgBillTrxInf(UUID billId, String subSpCode, String spSysId, Double billAmt, Double miscAmt,
            String billExprDt, String pyrId, String pyrName, String billDesc, String billGenDt,
            String billGenBy, String billApprBy, String pyrCellNum, String pyrEmail, String ccy,
            Double billEqvAmt, boolean remFlag, int billPayOpt, String payCntrNum, List<GepgBillItem> billItems) {
        this.billId = billId;
        this.subSpCode = subSpCode;
        this.spSysId = spSysId;
        this.billAmt = billAmt;
        this.miscAmt = miscAmt;
        this.billExprDt = billExprDt;
        this.pyrId = pyrId;
        this.pyrName = pyrName;
        this.billDesc = billDesc;
        this.billGenDt = billGenDt;
        this.billGenBy = billGenBy;
        this.billApprBy = billApprBy;
        this.pyrCellNum = pyrCellNum;
        this.pyrEmail = pyrEmail;
        this.ccy = ccy;
        this.billEqvAmt = billEqvAmt;
        this.remFlag = remFlag;
        this.billPayOpt = billPayOpt;
        this.payCntrNum = payCntrNum;
        this.billItems = billItems;
    }

    // Getters and Setters

    /**
     * Gets the bill ID.
     *
     * @return the bill ID
     */
    public UUID getBillId() {
        return billId;
    }

    /**
     * Sets the bill ID.
     *
     * @param billId the bill ID
     */
    public void setBillId(UUID billId) {
        this.billId = billId;
    }

    /**
     * Gets the sub service provider code.
     *
     * @return the sub service provider code
     */
    public String getSubSpCode() {
        return subSpCode;
    }

    /**
     * Sets the sub service provider code.
     *
     * @param subSpCode the sub service provider code
     */
    public void setSubSpCode(String subSpCode) {
        this.subSpCode = subSpCode;
    }

    /**
     * Gets the service provider system ID.
     *
     * @return the service provider system ID
     */
    public String getSpSysId() {
        return spSysId;
    }

    /**
     * Sets the service provider system ID.
     *
     * @param spSysId the service provider system ID
     */
    public void setSpSysId(String spSysId) {
        this.spSysId = spSysId;
    }

    /**
     * Gets the bill amount.
     *
     * @return the bill amount
     */
    public Double getBillAmt() {
        return billAmt;
    }

    /**
     * Sets the bill amount.
     *
     * @param billAmt the bill amount
     */
    public void setBillAmt(Double billAmt) {
        this.billAmt = billAmt;
    }

    /**
     * Gets the miscellaneous amount.
     *
     * @return the miscellaneous amount
     */
    public Double getMiscAmt() {
        return miscAmt;
    }

    /**
     * Sets the miscellaneous amount.
     *
     * @param miscAmt the miscellaneous amount
     */
    public void setMiscAmt(Double miscAmt) {
        this.miscAmt = miscAmt;
    }

    /**
     * Gets the bill expiration date.
     *
     * @return the bill expiration date
     */
    public String getBillExprDt() {
        return billExprDt;
    }

    /**
     * Sets the bill expiration date.
     *
     * @param billExprDt the bill expiration date
     */
    public void setBillExprDt(String billExprDt) {
        this.billExprDt = billExprDt;
    }

    /**
     * Gets the payer ID.
     *
     * @return the payer ID
     */
    public String getPyrId() {
        return pyrId;
    }

    /**
     * Sets the payer ID.
     *
     * @param pyrId the payer ID
     */
    public void setPyrId(String pyrId) {
        this.pyrId = pyrId;
    }

    /**
     * Gets the payer name.
     *
     * @return the payer name
     */
    public String getPyrName() {
        return pyrName;
    }

    /**
     * Sets the payer name.
     *
     * @param pyrName the payer name
     */
    public void setPyrName(String pyrName) {
        this.pyrName = pyrName;
    }

    /**
     * Gets the bill description.
     *
     * @return the bill description
     */
    public String getBillDesc() {
        return billDesc;
    }

    /**
     * Sets the bill description.
     *
     * @param billDesc the bill description
     */
    public void setBillDesc(String billDesc) {
        this.billDesc = billDesc;
    }

    /**
     * Gets the bill generation date.
     *
     * @return the bill generation date
     */
    public String getBillGenDt() {
        return billGenDt;
    }

    /**
     * Sets the bill generation date.
     *
     * @param billGenDt the bill generation date
     */
    public void setBillGenDt(String billGenDt) {
        this.billGenDt = billGenDt;
    }

    /**
     * Gets the bill generated by.
     *
     * @return the bill generated by
     */
    public String getBillGenBy() {
        return billGenBy;
    }

    /**
     * Sets the bill generated by.
     *
     * @param billGenBy the bill generated by
     */
    public void setBillGenBy(String billGenBy) {
        this.billGenBy = billGenBy;
    }

    /**
     * Gets the bill approved by.
     *
     * @return the bill approved by
     */
    public String getBillApprBy() {
        return billApprBy;
    }

    /**
     * Sets the bill approved by.
     *
     * @param billApprBy the bill approved by
     */
    public void setBillApprBy(String billApprBy) {
        this.billApprBy = billApprBy;
    }

    /**
     * Gets the payer cell number.
     *
     * @return the payer cell number
     */
    public String getPyrCellNum() {
        return pyrCellNum;
    }

    /**
     * Sets the payer cell number.
     *
     * @param pyrCellNum the payer cell number
     */
    public void setPyrCellNum(String pyrCellNum) {
        this.pyrCellNum = pyrCellNum;
    }

    /**
     * Gets the payer email.
     *
     * @return the payer email
     */
    public String getPyrEmail() {
        return pyrEmail;
    }

    /**
     * Sets the payer email.
     *
     * @param pyrEmail the payer email
     */
    public void setPyrEmail(String pyrEmail) {
        this.pyrEmail = pyrEmail;
    }

    /**
     * Gets the currency.
     *
     * @return the currency
     */
    public String getCcy() {
        return ccy;
    }

    /**
     * Sets the currency.
     *
     * @param ccy the currency
     */
    public void setCcy(String ccy) {
        this.ccy = ccy;
    }

    /**
     * Gets the bill equivalent amount.
     *
     * @return the bill equivalent amount
     */
    public Double getBillEqvAmt() {
        return billEqvAmt;
    }

    /**
     * Sets the bill equivalent amount.
     *
     * @param billEqvAmt the bill equivalent amount
     */
    public void setBillEqvAmt(Double billEqvAmt) {
        this.billEqvAmt = billEqvAmt;
    }

    /**
     * Checks if the reminder flag is set.
     *
     * @return true if the reminder flag is set, false otherwise
     */
    public boolean isRemFlag() {
        return remFlag;
    }

    /**
     * Sets the reminder flag.
     *
     * @param remFlag the reminder flag
     */
    public void setRemFlag(boolean remFlag) {
        this.remFlag = remFlag;
    }

    /**
     * Gets the bill payment option.
     *
     * @return the bill payment option
     */
    public int getBillPayOpt() {
        return billPayOpt;
    }

    /**
     * Sets the bill payment option.
     *
     * @param billPayOpt the bill payment option
     */
    public void setBillPayOpt(int billPayOpt) {
        this.billPayOpt = billPayOpt;
    }

    /**
     * Gets the payment control number.
     *
     * @return the payment control number
     */
    public String getPayCntrNum() {
        return payCntrNum;
    }

    /**
     * Sets the payment control number.
     *
     * @param payCntrNum the payment control number
     */
    public void setPayCntrNum(String payCntrNum) {
        this.payCntrNum = payCntrNum;
    }

    /**
     * Gets the list of bill items.
     *
     * @return the list of bill items
     */
    public List<GepgBillItem> getBillItems() {
        return billItems;
    }

    /**
     * Sets the list of bill items.
     *
     * @param billItems the list of bill items
     */
    public void setBillItems(List<GepgBillItem> billItems) {
        this.billItems = billItems;
    }

    /**
     * Generates a string representation of the object.
     *
     * @return a string representation of the object
     */
    @Override
    public String toString() {
        return "BillTrxInf{" +
                "billId='" + billId + '\'' +
                ", subSpCode='" + subSpCode + '\'' +
                ", spSysId='" + spSysId + '\'' +
                ", billAmt=" + billAmt +
                ", miscAmt=" + miscAmt +
                ", billExprDt=" + billExprDt +
                ", pyrId='" + pyrId + '\'' +
                ", pyrName='" + pyrName + '\'' +
                ", billDesc='" + billDesc + '\'' +
                ", billGenDt=" + billGenDt +
                ", billGenBy='" + billGenBy + '\'' +
                ", billApprBy='" + billApprBy + '\'' +
                ", pyrCellNum='" + pyrCellNum + '\'' +
                ", pyrEmail='" + pyrEmail + '\'' +
                ", ccy='" + ccy + '\'' +
                ", billEqvAmt=" + billEqvAmt +
                ", remFlag=" + remFlag +
                ", billPayOpt=" + billPayOpt +
                ", payCntrNum=" + payCntrNum +
                ", billItems=" + billItems +
                '}';
    }
}
