# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Gradle

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            TZ: "UTC" # Set the time zone

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: "adopt"
                  java-version: "11"
            - name: Verify locale
              run: |
                  sudo apt-get install -y locales
                  sudo locale-gen en_US.UTF-8
                  export LANG=en_US.UTF-8
            - name: Build with Gradle
              run: ./gradlew build
